import { db } from "./index";
import { companiesTable } from "./schema/companies";

const companies = [
  {
    name: "Google",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_\"G\"_logo.svg/1200px-Google_\"G\"_logo.svg.png",
    primaryColor: "#4285F4",
    secondaryColor: "#34A853",
    description: "Google's mission is to organize the world's information and make it universally accessible and useful.",
    foundedYear: 1998,
    headquarters: "Mountain View, California, USA",
    website: "https://about.google",
    linkedin: "https://linkedin.com/company/google",
    twitter: "https://twitter.com/google",
    companySize: "100,000+ employees",
    industry: "Technology",
    culture: "Focus on innovation, collaboration, and making a positive impact on the world.",
    benefits: "Comprehensive health insurance, free meals, professional development, on-site fitness centers.",
    type: "corporate"
  },
  {
    name: "Microsoft",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1024px-Microsoft_logo.svg.png",
    primaryColor: "#F25022",
    secondaryColor: "#7FBA00",
    description: "Our mission is to empower every person and every organization on the planet to achieve more.",
    foundedYear: 1975,
    headquarters: "Redmond, Washington, USA",
    website: "https://microsoft.com",
    linkedin: "https://linkedin.com/company/microsoft",
    twitter: "https://twitter.com/microsoft",
    companySize: "100,000+ employees",
    industry: "Technology",
    culture: "Growth mindset, diversity and inclusion, customer obsession.",
    benefits: "Generous time off, health and wellness programs, retirement savings plan.",
    type: "corporate"
  },
  {
    name: "Amazon",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1200px-Amazon_logo.svg.png",
    primaryColor: "#FF9900",
    secondaryColor: "#000000",
    description: "Earth's most customer-centric company, where customers can find and discover anything they might want to buy online.",
    foundedYear: 1994,
    headquarters: "Seattle, Washington, USA",
    website: "https://aboutamazon.com",
    linkedin: "https://linkedin.com/company/amazon",
    twitter: "https://twitter.com/amazon",
    companySize: "1,000,000+ employees",
    industry: "E-commerce & Cloud Computing",
    culture: "Leadership Principles, day 1 mentality, customer obsession.",
    benefits: "Medical, dental, vision insurance, 401(k) with company match.",
    type: "corporate"
  },
  {
    name: "TCS",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/1200px-Tata_Consultancy_Services_Logo.svg.png",
    primaryColor: "#0066CC",
    secondaryColor: "#004B99",
    description: "A purpose-led organization that is building a meaningful future through innovation, technology, and collective knowledge.",
    foundedYear: 1968,
    headquarters: "Mumbai, India",
    website: "https://tcs.com",
    linkedin: "https://linkedin.com/company/tata-consultancy-services",
    twitter: "https://twitter.com/tcs",
    companySize: "600,000+ employees",
    industry: "IT Services",
    culture: "Integrity, excellence, respect for the individual, learning and sharing.",
    benefits: "Health insurance, performance-based bonuses, training and development.",
    type: "corporate"
  },
  {
    name: "Infosys",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/1280px-Infosys_logo.svg.png",
    primaryColor: "#2C6E9E",
    secondaryColor: "#007CC3",
    description: "A global leader in next-generation digital services and consulting.",
    foundedYear: 1981,
    headquarters: "Bengaluru, India",
    website: "https://infosys.com",
    linkedin: "https://linkedin.com/company/infosys",
    twitter: "https://twitter.com/infosys",
    companySize: "300,000+ employees",
    industry: "IT Services",
    culture: "C-LIFE: Client focus, Leadership by example, Integrity and transparency, Fairness, Pursuit of Excellence.",
    benefits: "Comprehensive benefits package, work-life balance, employee welfare programs.",
    type: "corporate"
  },
  {
    name: "Wipro",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/1200px-Wipro_Primary_Logo_Color_RGB.svg.png",
    primaryColor: "#1D1D1D",
    secondaryColor: "#6C3483",
    description: "Leading technology services and consulting company focused on building innovative solutions.",
    foundedYear: 1945,
    headquarters: "Bengaluru, India",
    website: "https://wipro.com",
    linkedin: "https://linkedin.com/company/wipro",
    twitter: "https://twitter.com/wipro",
    companySize: "250,000+ employees",
    industry: "IT Services",
    culture: "Spirit of Wipro: Be passionate about clients' success, Treat each person with respect, Be global and responsible, Unyielding integrity.",
    benefits: "Health care, financial wellbeing, personal development.",
    type: "corporate"
  },
  {
    name: "HCL Tech",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/HCL_Technologies_logo.svg/1200px-HCL_Technologies_logo.svg.png",
    primaryColor: "#005696",
    secondaryColor: "#00AEEF",
    description: "Supercharging progress for the world's leading enterprises.",
    foundedYear: 1976,
    headquarters: "Noida, India",
    website: "https://hcltech.com",
    linkedin: "https://linkedin.com/company/hcltech",
    twitter: "https://twitter.com/hcltech",
    companySize: "220,000+ employees",
    industry: "IT Services",
    culture: "Ideapreneurship, trust, transparency, and value centricity.",
    benefits: "Medical insurance, annual health checkups, life insurance.",
    type: "corporate"
  },
  {
    name: "Tech Mahindra",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Tech_Mahindra_logo.svg/1200px-Tech_Mahindra_logo.svg.png",
    primaryColor: "#E31837",
    secondaryColor: "#000000",
    description: "Connected World. Connected Experiences.",
    foundedYear: 1986,
    headquarters: "Pune, India",
    website: "https://techmahindra.com",
    linkedin: "https://linkedin.com/company/tech-mahindra",
    twitter: "https://twitter.com/tech_mahindra",
    companySize: "150,000+ employees",
    industry: "IT Services",
    culture: "Rise: Accept no limits, alternative thinking, driving positive change.",
    benefits: "Employee assistance programs, career growth opportunities.",
    type: "corporate"
  },
  {
    name: "Accenture",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Accenture.svg/1280px-Accenture.svg.png",
    primaryColor: "#A100FF",
    secondaryColor: "#000000",
    description: "Delivering on the promise of technology and human ingenuity.",
    foundedYear: 1989,
    headquarters: "Dublin, Ireland",
    website: "https://accenture.com",
    linkedin: "https://linkedin.com/company/accenture",
    twitter: "https://twitter.com/accenture",
    companySize: "700,000+ employees",
    industry: "Management Consulting & IT Services",
    culture: "Client value creation, one global network, integrity, stewardship.",
    benefits: "Competitive pay, comprehensive health insurance, retirement plans.",
    type: "corporate"
  },
  {
    name: "IBM",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/IBM_logo.svg/1200px-IBM_logo.svg.png",
    primaryColor: "#006699",
    secondaryColor: "#000000",
    description: "IBMers believe in progress—that the application of intelligence, reason and science can improve business, society and the human condition.",
    foundedYear: 1911,
    headquarters: "Armonk, New York, USA",
    website: "https://ibm.com",
    linkedin: "https://linkedin.com/company/ibm",
    twitter: "https://twitter.com/ibm",
    companySize: "280,000+ employees",
    industry: "Technology & Consulting",
    culture: "Dedication to every client's success, innovation that matters, trust and personal responsibility.",
    benefits: "Health and wellness, financial security, growth and development.",
    type: "corporate"
  },
  {
    name: "SSC",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Staff_Selection_Commission_Logo.png/220px-Staff_Selection_Commission_Logo.png",
    primaryColor: "#FF9933",
    secondaryColor: "#128807",
    description: "Staff Selection Commission (SSC) is an organization under Government of India to recruit staff for various posts in the various Ministries and Departments of the Government of India and in Subordinate Offices.",
    foundedYear: 1975,
    headquarters: "New Delhi, India",
    website: "https://ssc.nic.in",
    linkedin: "",
    twitter: "",
    companySize: "Government Body",
    industry: "Government",
    culture: "Integrity, impartiality, and efficiency in recruitment.",
    benefits: "Government job security, pension, medical benefits, housing allowance.",
    type: "government"
  },
  {
    name: "UPSC",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Union_Public_Service_Commission_logo.png/220px-Union_Public_Service_Commission_logo.png",
    primaryColor: "#FF9933",
    secondaryColor: "#000080",
    description: "The Union Public Service Commission (UPSC) is India's premier central recruiting agency for Group 'A' officers.",
    foundedYear: 1926,
    headquarters: "New Delhi, India",
    website: "https://upsc.gov.in",
    linkedin: "",
    twitter: "",
    companySize: "Government Body",
    industry: "Government",
    culture: "Merit-based selection for civil services.",
    benefits: "Prestigious career, social impact, comprehensive government benefits.",
    type: "government"
  },
  {
    name: "KPSC",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Emblem_of_Karnataka.svg/1200px-Emblem_of_Karnataka.svg.png",
    primaryColor: "#FFD700",
    secondaryColor: "#CE1126",
    description: "Karnataka Public Service Commission (KPSC) is the state agency authorized to conduct the Civil Services Examination for entry-level appointments to the various civil services of Karnataka.",
    foundedYear: 1951,
    headquarters: "Bengaluru, Karnataka, India",
    website: "https://kpsc.kar.nic.in",
    linkedin: "",
    twitter: "",
    companySize: "State Government Body",
    industry: "Government",
    culture: "Fair and transparent recruitment for state services.",
    benefits: "State government job security, pension, allowances.",
    type: "government"
  },
  {
    name: "Oracle",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Oracle_logo.svg/1200px-Oracle_logo.svg.png",
    primaryColor: "#F80000",
    secondaryColor: "#000000",
    description: "Our mission is to help people see data in new ways, discover insights, unlock endless possibilities.",
    foundedYear: 1977,
    headquarters: "Austin, Texas, USA",
    website: "https://oracle.com",
    linkedin: "https://linkedin.com/company/oracle",
    twitter: "https://twitter.com/oracle",
    companySize: "140,000+ employees",
    industry: "Technology",
    culture: "Innovation-led, results-driven, customer-centric.",
    benefits: "Comprehensive benefits, flexible work, retirement planning.",
    type: "corporate"
  },
  {
    name: "Cisco",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Cisco_logo_blue_2016.svg/1200px-Cisco_logo_blue_2016.svg.png",
    primaryColor: "#00BCEB",
    secondaryColor: "#017CAD",
    description: "Cisco helps companies seize the opportunities of tomorrow by proving that amazing things can happen when you connect the unconnected.",
    foundedYear: 1984,
    headquarters: "San Jose, California, USA",
    website: "https://cisco.com",
    linkedin: "https://linkedin.com/company/cisco",
    twitter: "https://twitter.com/cisco",
    companySize: "80,000+ employees",
    industry: "Networking & Technology",
    culture: "Conscious Culture: Inclusive, collaborative, and socially responsible.",
    benefits: "Time to give, tuition reimbursement, health and wellness.",
    type: "corporate"
  },
  {
    name: "Dell",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Dell_logo_2016.svg/1200px-Dell_logo_2016.svg.png",
    primaryColor: "#006BB6",
    secondaryColor: "#0085C3",
    description: "Dell Technologies is a unique family of businesses that helps organizations and individuals build their digital future and transform how they work, live and play.",
    foundedYear: 1984,
    headquarters: "Round Rock, Texas, USA",
    website: "https://dell.com",
    linkedin: "https://linkedin.com/company/delltechnologies",
    twitter: "https://twitter.com/dell",
    companySize: "130,000+ employees",
    industry: "Technology",
    culture: "Innovation, integrity, and social impact.",
    benefits: "Flexible work arrangements, health insurance, career development.",
    type: "corporate"
  },
  {
    name: "Intel",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Intel_logo_%282020%29.svg/1200px-Intel_logo_%282020%29.svg.png",
    primaryColor: "#0068B5",
    secondaryColor: "#00C7FD",
    description: "Intel's mission is to shape the future of technology to help create a better world.",
    foundedYear: 1968,
    headquarters: "Santa Clara, California, USA",
    website: "https://intel.com",
    linkedin: "https://linkedin.com/company/intel-corporation",
    twitter: "https://twitter.com/intel",
    companySize: "120,000+ employees",
    industry: "Semiconductors & Technology",
    culture: "Quality, speed, innovation, and trust.",
    benefits: "Stock programs, health insurance, wellness centers.",
    type: "corporate"
  },
  {
    name: "IBPS",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Institute_of_Banking_Personnel_Selection_Logo.png/220px-Institute_of_Banking_Personnel_Selection_Logo.png",
    primaryColor: "#003399",
    secondaryColor: "#FFFFFF",
    description: "Institute of Banking Personnel Selection (IBPS) is an autonomous body set up to evolve and implement world class processes of assessment and selection of personnel for various client organizations.",
    foundedYear: 1975,
    headquarters: "Mumbai, India",
    website: "https://ibps.in",
    linkedin: "",
    twitter: "",
    companySize: "Autonomous Body",
    industry: "Banking Recruitment",
    culture: "Fairness, speed, and accuracy in evaluation.",
    benefits: "Prestigious recruitment body role, professional environment.",
    type: "government"
  },
  {
    name: "RRB",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Indian_Railways_Logo.svg/1200px-Indian_Railways_Logo.svg.png",
    primaryColor: "#800000",
    secondaryColor: "#FFD700",
    description: "Railway Recruitment Board (RRB) is a government organization in India that was set up by the Ministry of Railways to manage the recruitment of new employees to work in Indian Railways.",
    foundedYear: 1998,
    headquarters: "New Delhi, India",
    website: "https://indianrailways.gov.in",
    linkedin: "",
    twitter: "",
    companySize: "Government Body",
    industry: "Railways",
    culture: "Service to the nation, integrity, and teamwork.",
    benefits: "Railway quarters, free travel passes, pension, medical benefits.",
    type: "government"
  },
  {
    name: "Flipkart",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Flipkart_logo.svg/1200px-Flipkart_logo.svg.png",
    primaryColor: "#2874F0",
    secondaryColor: "#FFE11B",
    description: "Flipkart is India's leading e-commerce marketplace.",
    foundedYear: 2007,
    headquarters: "Bengaluru, India",
    website: "https://flipkart.com",
    linkedin: "https://linkedin.com/company/flipkart",
    twitter: "https://twitter.com/flipkart",
    companySize: "30,000+ employees",
    industry: "E-commerce",
    culture: "Innovation, customer-first, audacity.",
    benefits: "Comprehensive insurance, learning opportunities, ESOPs.",
    type: "corporate"
  },
  {
    name: "Zomato",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Zomato_Logo.svg/1200px-Zomato_Logo.svg.png",
    primaryColor: "#E23744",
    secondaryColor: "#FFFFFF",
    description: "Zomato's mission is better food for more people.",
    foundedYear: 2008,
    headquarters: "Gurugram, India",
    website: "https://zomato.com",
    linkedin: "https://linkedin.com/company/zomato",
    twitter: "https://twitter.com/zomato",
    companySize: "5,000+ employees",
    industry: "Food Delivery & Technology",
    culture: "Hungry for better, ownership, resilience.",
    benefits: "Period leave, paternal leave, insurance.",
    type: "corporate"
  },
  {
    name: "Swiggy",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/1200px-Swiggy_logo.svg.png",
    primaryColor: "#FC8019",
    secondaryColor: "#FFFFFF",
    description: "Swiggy is India's leading on-demand delivery platform.",
    foundedYear: 2014,
    headquarters: "Bengaluru, India",
    website: "https://swiggy.com",
    linkedin: "https://linkedin.com/company/swiggy-in",
    twitter: "https://twitter.com/swiggy",
    companySize: "5,000+ employees",
    industry: "Food Delivery & Technology",
    culture: "Customer obsession, striving for excellence, being humble.",
    benefits: "Health benefits, skill development, mental wellness support.",
    type: "corporate"
  }
];

export async function seedCompanies() {
  console.log("Seeding companies...");
  for (const company of companies) {
    try {
      await db.insert(companiesTable).values(company).onConflictDoUpdate({
        target: companiesTable.name,
        set: company
      });
    } catch (e) {
      console.error(`Error seeding ${company.name}:`, e);
    }
  }
  console.log("Finished seeding companies.");
}
